"""empty message

Revision ID: 1f070769fc4b
Revises: 6a3f54c2ab7e
Create Date: 2023-01-12 15:20:29.156533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f070769fc4b'
down_revision = '6a3f54c2ab7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cotizacion',
    sa.Column('cotizacion_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('monto_total', sa.Float(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('cotizacion_id')
    )
    op.create_table('cotizacion_producto',
    sa.Column('cotizacion_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizacion.cotizacion_id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.producto_id'], ),
    sa.PrimaryKeyConstraint('cotizacion_id', 'producto_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cotizacion_producto')
    op.drop_table('cotizacion')
    # ### end Alembic commands ###
