"""empty message

Revision ID: 9f4c04f58206
Revises: 1f070769fc4b
Create Date: 2023-01-13 17:22:31.028655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f4c04f58206'
down_revision = '1f070769fc4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotizacion_producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotizacion_producto', schema=None) as batch_op:
        batch_op.drop_column('cantidad')

    # ### end Alembic commands ###
