"""empty message

Revision ID: cab6275b8ec0
Revises: 
Create Date: 2022-12-01 20:49:33.167503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cab6275b8ec0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=True),
    sa.Column('padre_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('categoria_id')
    )
    op.create_table('producto',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('url_imagen', sa.String(length=255), nullable=True),
    sa.Column('imagen_extra', sa.String(length=255), nullable=True),
    sa.Column('detalle', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('producto_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto')
    op.drop_table('categoria')
    # ### end Alembic commands ###
